# Generated by Django 5.0 on 2026-03-27 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_doctorleave_doctorschedule_medicine_medicinestock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('gynecology', 'Gynecology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT Specialist'), ('psychiatry', 'Psychiatry'), ('dentistry', 'Dentistry'), ('radiology', 'Radiology'), ('surgery', 'General Surgery'), ('internal_medicine', 'Internal Medicine'), ('emergency', 'Emergency Medicine'), ('other', 'Other')], max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('languages', models.CharField(default='English', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
