# Generated by Django 5.0 on 2026-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_doctorprofile_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, help_text='General description or notes'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g., Strip, Bottle, Tablet', max_length=50),
        ),
    ]
