# Generated by Django 5.2.12 on 2026-03-26 07:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_doctorleave_doctorschedule_medicine_medicinestock_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='differential_diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='duration_of_symptoms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='investigations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='physical_examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='referred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('referred', 'Referred'), ('admitted', 'Admitted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='visit_type',
            field=models.CharField(choices=[('opd', 'OPD'), ('ipd', 'IPD'), ('emergency', 'Emergency'), ('followup', 'Follow-up')], default='opd', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='alcohol_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='exercise_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_surgeries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_refillable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='hospitals.medicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 26, 7, 45, 52, 387278, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='refill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, help_text='Legacy free-text duration', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('thrice_daily', 'Thrice Daily'), ('four_times_daily', 'Four Times Daily'), ('every_6_hours', 'Every 6 Hours'), ('every_8_hours', 'Every 8 Hours'), ('every_12_hours', 'Every 12 Hours'), ('as_needed', 'As Needed'), ('before_meal', 'Before Meal'), ('after_meal', 'After Meal'), ('bedtime', 'At Bedtime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(help_text='Manual entry if medicine not in master list', max_length=255),
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('xray', 'X-Ray'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('discharge_summary', 'Discharge Summary'), ('referral', 'Referral Letter'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='patient_documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
